//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyQuestionsConfigurator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurveyQuestionsConfigurator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the following Question?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the database was successful.
        /// </summary>
        internal static string ConnectionSuccess {
            get {
                return ResourceManager.GetString("ConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to database check connection string.
        /// </summary>
        internal static string DatabaseConnectionError {
            get {
                return ResourceManager.GetString("DatabaseConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A database error occurred. Please check try again.
        /// </summary>
        internal static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteCaption {
            get {
                return ResourceManager.GetString("DeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End caption cannot be empty or white space.
        /// </summary>
        internal static string EndCaptionEmptyError {
            get {
                return ResourceManager.GetString("EndCaptionEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered value is too long..
        /// </summary>
        internal static string LengthTooLongError {
            get {
                return ResourceManager.GetString("LengthTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required value is missing (null)..
        /// </summary>
        internal static string NullError {
            get {
                return ResourceManager.GetString("NullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required field cannot be empty or whitespace..
        /// </summary>
        internal static string NullOrWhiteSpaceError {
            get {
                return ResourceManager.GetString("NullOrWhiteSpaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is out of the allowed range..
        /// </summary>
        internal static string OutOfRangeError {
            get {
                return ResourceManager.GetString("OutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text cannot be more than 1000 characters.
        /// </summary>
        internal static string QuestionLengthError {
            get {
                return ResourceManager.GetString("QuestionLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string QuestionOrder {
            get {
                return ResourceManager.GetString("QuestionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestionText.
        /// </summary>
        internal static string QuestionText {
            get {
                return ResourceManager.GetString("QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string QuestionType {
            get {
                return ResourceManager.GetString("QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        internal static string QuestionType_Slider {
            get {
                return ResourceManager.GetString("QuestionType_Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiley.
        /// </summary>
        internal static string QuestionType_Smiley {
            get {
                return ResourceManager.GetString("QuestionType_Smiley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        internal static string QuestionType_Star {
            get {
                return ResourceManager.GetString("QuestionType_Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider end value cannot be less than slider start value.
        /// </summary>
        internal static string SliderEndValueError {
            get {
                return ResourceManager.GetString("SliderEndValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider start value cannot be more or equal to slider end value.
        /// </summary>
        internal static string SliderStartValueError {
            get {
                return ResourceManager.GetString("SliderStartValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of smiley faces cannot be less than 2 or more than 5.
        /// </summary>
        internal static string SmileyFacesNumberError {
            get {
                return ResourceManager.GetString("SmileyFacesNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred while updating the questions in real time. Changes made by other users may not appear immediately. Please contact your administrator if the issue persists..
        /// </summary>
        internal static string SqlTableDependencyError {
            get {
                return ResourceManager.GetString("SqlTableDependencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of stars cannot be less than 1.
        /// </summary>
        internal static string StarsNumberError {
            get {
                return ResourceManager.GetString("StarsNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start caption cannot be empty or white space.
        /// </summary>
        internal static string StartCaptionEmptyError {
            get {
                return ResourceManager.GetString("StartCaptionEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessCaption {
            get {
                return ResourceManager.GetString("SuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error please try again.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown data type encountered..
        /// </summary>
        internal static string UnknownTypeError {
            get {
                return ResourceManager.GetString("UnknownTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed. Please check your input..
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
    }
}
